// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvmcoqjjjzlrnswytwlw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2bWNvcWpqanpscm5zd3l0d2x3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2Njk5NjAsImV4cCI6MjA2MTI0NTk2MH0.PtqV5hfh_17bcBRZe2Vx3RfwVonE_9ReMtRZ99c1Ib8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);